server:
   port: 8090
   servlet:
      context-path: /myschool
      
spring:
   mvc:
      view:
         prefix:   /WEB-INF/
         suffix:   .jsp
      security:
         user:
            name: user
            password: user
      messeges:
         cache-duration: 10
         basename: messages_en_us
         
security:
   oauth2:
      client:
         client-id: clientuser
         client-secret: clientsecret
         authentication-scheme: header
         client-authentication-scheme: form
         grant-type: client-credentials
         accessTokenUri: http://localhost:8070/oauth/token
         user-authorization-uri: htp://localhost:8070/validateuser
         
logging:
   level:
      org.springframework.web.client: TRACE
      org.springframework.http.client: TRACE
      org.springframework.security: TRACE
      org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
      
apiURL: http://localhost:9090/studentenrollment